#!/bin/bash
spaces=" |'"
program="bin/sota"
python=`which python2`
commandline=()
for arg in "$@"; do
    case $arg in
        --pdb)
        program="$python -m pdb src/target.py"
        ;;
        --py)
        program="$python src/target.py"
        ;;
        *)
        if [[ $arg =~ $spaces ]]; then
            arg="'$arg'"
        fi
        commandline+=("${arg}")
        ;;
    esac
done
cmd="LD_LIBRARY_PATH=lib:$LD_LIBRARY_PATH ${program} ${commandline[@]}"
eval "$cmd"
exit $?
